site_name: 'Judy'
site_description: 'Judy Heflin's internet place'
site_author: 'Judy Heflin'
repo_name: 'judyheflin/judyheflin.github.io'
repo_url: 'https://github.com/judyheflin/judyheflin.github.io'
copyright: 'Copyright &copy; 2021 judy'
docs_dir: 'blog'
nav:
- Home:
  - Overview: 'index.md'
- About:
  - About: 'about/about.md'
- Books:
  - Computer-Generated Books: 'computer-generated-books.md'
extra:
  social:
  - icon: 'fontawesome/brands/twitter'
    link: 'https://twitter.com/judyhefl_in'
theme:
  name: 'material'
  features:
  - navigation.tabs
  - navigation.instant
  - navigation.top
  custom_dir: 'theme'
  font:
      text: 'Oxygen'
      code: 'Oxygen Mono'
  palette:
    primary: 'blue'
  highlightjs: true
  hljs_languages:
  - 'yaml'
  - 'json'
  - 'bash'
markdown_extensions:
- pymdownx.snippets
- meta
- toc:
    permalink: true
- admonition
- codehilite:
    linenums: False # linenums in codeblock did not play well with numbered list and provided bad experience
plugins:
- search
- macros:
    include_dir: 'docs/contents/snippets'
- awesome-pages
